# Generated by Django 4.2.4 on 2023-08-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='identity_piece',
            field=models.CharField(choices=[(True, 'Verified'), (False, 'Unverified')], max_length=1024),
        ),
    ]
