# Generated by Django 4.2.4 on 2023-08-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_seller_identity_piece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='identity_piece',
            field=models.ImageField(upload_to='identity_images/'),
        ),
    ]
